[project]
name = "TaskManager"
version = "0.1.0"
description = "A simple python CLI task manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logging>=0.4.9.6",
    "typing>=3.10.0.0",
]
